name: supabase_functions_example
description: A Supabase Edge Function written in Dart.
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  edge: ^0.0.7
  supabase_functions: ^0.0.2+4