name: deno_deploy
description: Runtime APIs for running Dart Edge on Deno Deploy environments.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/deno_deploy
version: 0.0.1-dev.6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  js: ^0.6.5
  edge_runtime: 
    git: 
      url: https://github.com/Mattertorian/dart_edge.git
      path: packages/edge_runtime
  typings: ^0.0.6+3
