name: cloudflare_workers_example
description: An example Cloudflare Worker written in Dart.
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloudflare_workers: 0.0.4+4
  edge: ^0.0.7