name: supabase_functions
description: Write and deploy Dart functions to Supabase Functions.
homepage: https://dartedge.dev
publish_to: none
# repository: https://github.com/invertase/dart_edge/tree/main/packages/supabase_functions
version: 0.0.2+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  deno_deploy: ^0.0.1-dev.6
  # edge: ^0.0.7
  edge: 
    git: 
      url: https://github.com/Mattertorian/dart_edge.git
      path: packages/edge
  # edge_runtime: ^0.0.4+2
  edge_runtime: 
    git: 
      url: https://github.com/Mattertorian/dart_edge.git
      path: packages/edge_runtime
  js: ^0.6.5
  typings: ^0.0.6+3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
